keycloak:
  auth-server-url: http://192.168.0.232:8442
  realm: test-keycloack
  resource: my-app
  redirect-uri: http://localhost:8080/api/v1/auth/callback
  client-secret: TTFktBmVl3iD05c6upf9QyT68srXo7mF
